### ISSUE TITLE
Migrate off of private bintray repository

### ISSUE THREAD

**Issue by jrouly** [OpenAPITools/sbt-openapi-generator#35]
Bintray was sunset a while ago. Artifacts can no longer be published against it.

What is the plan for the OpenAPITools repository more broadly for artifact management?

**Comment by jrouly** [comment]
@wing328 is this something you could help out with? I don't really have any context on where the other mainline OpenAPITools projects publish.

**Comment by nMoncho** [comment]
@jrouly @wing328 Would it possible to publish the plugin at https://scala.jfrog.io/ui/native/sbt-plugin-releases/org.openapitools/sbt-openapi-generator, this is were we get redirected from https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases

**Comment by monksy** [comment]
Looks like much of the other sbt-openapi generator projects are being published on the central repo. Why isn't this? 

I can't seem to use the plugin because it doesn't know where to grab it.

**Comment by russellremple** [comment]
same

**Comment by ckipp01** [comment]
@jrouly would you be open to a PR addressing this? I see there are other artifacts being pushed to Maven centeral here: https://repo1.maven.org/maven2/org/openapitools/. I'm happy to send in a pr adding in https://github.com/sbt/sbt-ci-release, which is what a lot of open source sbt plugins are using. All you'd need to do is ensure the env variables are added to this repository. That's assuming you have access to the key to sign and the sonatype creds. If I sent in a PR adding this would you be able to update the secrets and push a release?

This is sort of a last effort before we fork and publish this internally, which we'd love to avoid.

**Comment by jrouly** [comment]
Apologies for my absence, thanks for taking this on @ckipp01 it's much appreciated.
