### ISSUE TITLE
Plugin repository not found

### ISSUE THREAD

**Issue by Bartlomiej-Ozieblo** [OpenAPITools/sbt-openapi-generator#46]
Hi,

Today we found problem with getting openapi generator plugin from maven repository.

`
sbt.librarymanagement.ResolveException: Error downloading org.openapitools:sbt-openapi-generator;sbtVersion=1.0;scalaVersion=2.12:5.0.1
`

Link for artefact `https://repo1.maven.org/maven2/org/openapitools/sbt-openapi-generator_2.12_1.0/5.0.1/sbt-openapi-generator-5.0.1.pom` seems down.

Is there any solution or workaround?

**Comment by wing328** [comment]
just published to https://repo1.maven.org/maven2/org/openapitools/sbt-openapi-generator_2.12_1.0/7.3.0/

can you please give it another try?
